### ISSUE TITLE
Compilation fails after commit 23de5b8

### ISSUE THREAD

**Issue by Rhiannon81** [clsid2/mpc-hc#2179]
Since commit [23de5b8](https://github.com/clsid2/mpc-hc/commit/23de5b85cfe50a32c3dbfbd3572ab8f7dd3d8aa5) I am unable to build MPC-HC.
Everything is up to date (MSYS, MinGW, VS etc.).

`C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(54,46): error C3556: 'GetDpiForWindow': incorrect argument to 'decltype' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(55,25): error C2641: cannot deduce template arguments for 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(55,25): error C2780: 'WinapiFunc<<unnamed-symbol>> WinapiFunc(void)': expects 0 arguments - 2 provided [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(55,25): error C2780: 'WinapiFunc<<unnamed-symbol>> WinapiFunc(WinapiFunc<<unnamed-symbol>>)': expects 1 arguments - 2 provided [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(56,9): error C2451: a conditional expression of type 'const WinapiFunc' is not valid [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(56,9): message : use of undefined type 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' (compiling source file DpiHelper.cpp) [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(57,16): error C2064: term does not evaluate to a function taking 1 arguments [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(105,57): error C3556: 'SystemParametersInfoForDpi': incorrect argument to 'decltype' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(106,40): error C2641: cannot deduce template arguments for 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(106,40): error C2780: 'WinapiFunc<<unnamed-symbol>> WinapiFunc(void)': expects 0 arguments - 2 provided [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(106,40): error C2780: 'WinapiFunc<<unnamed-symbol>> WinapiFunc(WinapiFunc<<unnamed-symbol>>)': expects 1 arguments - 2 provided [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(112,9): error C2451: a conditional expression of type 'const WinapiFunc' is not valid [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(112,9): message : use of undefined type 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' (compiling source file DpiHelper.cpp) [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(113,13): error C2064: term does not evaluate to a function taking 5 arguments [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(125,53): error C3556: 'GetSystemMetricsForDpi': incorrect argument to 'decltype' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(126,36): error C2641: cannot deduce template arguments for 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(126,36): error C2780: 'WinapiFunc<<unnamed-symbol>> WinapiFunc(void)': expects 0 arguments - 2 provided [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(126,36): error C2780: 'WinapiFunc<<unnamed-symbol>> WinapiFunc(WinapiFunc<<unnamed-symbol>>)': expects 1 arguments - 2 provided [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(130,9): error C2451: a conditional expression of type 'const WinapiFunc' is not valid [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(130,9): message : use of undefined type 'WinapiFunc' [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\DSUtil\WinapiFunc.h(24,7): message : see declaration of 'WinapiFunc' (compiling source file DpiHelper.cpp) [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(132,16): error C2064: term does not evaluate to a function taking 1 arguments [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]
C:\mpc-hc\src\mpc-hc\DpiHelper.cpp(135,19): error C2064: term does not evaluate to a function taking 1 arguments [C:\mpc-hc\src\mpc-hc\mpc-hc.vcxproj]`

**Comment by clsid2** [comment]
Git head compiles fine for me.

**Comment by avapug** [comment]
You get this error if you don't use Windows 8.1 SDK to build.
